services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: atcreations-frontend_${NODE_ENV}
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: production
    restart: always
    command: npm start