services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: at-frontend-${NODE_ENV}
    image: at-frontend-${NODE_ENV}
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
    restart: always
    command: npm start