name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run build
        run: npm run build

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H server-1.atcreations.ca >> ~/.ssh/known_hosts

      - name: Copy files to server
        run: rsync -avz --delete --exclude '.git*' ./ deploy@server-1.atcreations.ca:/home/deploy/atstore-front/

      - name: Copy environment file
        run: |
          ssh deploy@server-1.atcreations.ca <<EOF
          cp /home/deploy/env/atstore-front.env /home/deploy/atstore-front/.env
          EOF

      - name: Deploy with Docker Compose
        run: |
          ssh deploy@server-1.atcreations.ca <<EOF
          cd /home/deploy/atstore-front/
          mkdir -p .next
          docker compose build --no-cache
          docker compose up -d
          EOF
